server:
  port: 8083

spring:
  application:
    name: zuul-server

zuul:
  routes:
    products:
      path: /api/v1/**
      url: https://localhost:2222/
      strip-prefix: false
 
    feign:
      path: /api/v1/**
      url: http://localhost:8080/
      strip-prefix: false

  ssl-hostname-validation-enabled: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    
    fetch-registry: true
    
    service-url:
     defaultzone: http://localhost:8761/eureka/
     
management:
  endpoint:
    routes:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: "*"